version: "3.9"

services:
  web:
    build:
      context: .
      args:
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH}
    container_name: coursework
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./public/slides:/app/public/slides
    networks:
      - proxy-net
    env_file:
      - .env
networks:
  proxy-net:
    external: true
